### Récupère toutes les users OK

GET http://localhost:5000/api/users

### Crèe une user OK

POST http://localhost:5000/api/users
content-type: application/json

{
    "fname": "Mario",
    "lname": "Broz",
    "email": "marios@vdb.fr",
    "companyrole": "sailor"
}
### Récupère une user Ok

GET http://localhost:3000/api/users/3

### Modifie une user OK

PATCH http://localhost:3000/api/users/2
content-type: application/json


{
    "fname": "Didier",
    "lname": "Dupré",
    "email": "didier@vdb.fr",
    "companyrole": "sailor"
}

### Supprime une user OK

DELETE  http://localhost:3000/api/users/7

### Récupère tous les trips OK
GET http://localhost:5000/api/trips

### Crèe un trip OK

POST http://localhost:5000/api/trips
content-type: application/json

{
    "type_trip": "navette",
    "boat": "Bréhatine",
    "harbour": "Acouest",
    "departure": "17:40",
    "arrival": "18:40",
    "day_trip": "13/07/22",
    "quantity": 57,
    "delay_trip": "false",
    "reason": "",
    "user_id_": 2
}

### Récupère un trip OK

GET http://localhost:3000/api/trips/1

### Modifie un trip OK

PATCH http://localhost:3000/api/trips/5
content-type: application/json

{
    "type_trip": "navette",
    "boat": "Bréhatine",
    "harbour": "Acouest",
    "departure": "17:40",
    "arrival": "19:40",
    "day_trip": "13/07/22",
    "quantity": 59,
    "delay_trip": true,
    "reason": "blabla",
    "user_id_": 2
}

### Supprime un trip OK

DELETE  http://localhost:3000/api/trips/5

### Login

POST http://localhost:5000/api/login
content-type: application/json

{
    "email": "carlos@vvdb.fr",
    "password": "Hello22+"
}