### Récupère toutes les users OK

GET http://localhost:5000/api/users

### Crèe une user OK

POST http://localhost:5000/api/users
content-type: application/json

{
    "fname": "Mario",
    "lname": "Broz",
    "email": "marios@vdb.fr",
    "password": "cdcvfvffvfv",
    "admin": "false"
}




### Récupère une user Ok

GET http://process.ENV.URL/api/users/3



### Modifie une user OK

PATCH http://process.ENV.URL/api/users/2
content-type: application/json

{
    "fname": "Didier",
    "lname": "Dupré",
    "email": "didier@vdb.fr",
    "companyrole": "sailor"
}

### Supprime une user OK

DELETE  http://process.ENV.URL/api/users/7

### Récupère tous les trips OK
GET http://localhost:5000/api/trips

### Récupère tous les trips entre deux dates (pour le excel)
POST http://localhost:5000/api/trips/excel
content-type: application/json

{
    "start": "24/12/2022",
    "end": "26/12/2022"
}

### Crèe un trip OK

POST http://localhost:5000/api/trips
content-type: application/json

{
  "boat": "Bréhatine",
  "type_trip": "Directe",
  "harbour": "Arcouest",
  "quantity": 7,
  "day_trip": "2022-12-25",
  "departure": "15:15",
  "arrival": "00:00",
  "delay_trip": "false",
  "reason": "",
  "user_id_": 1
}

### Récupère un trip OK

GET http://localhost:5000/api/trips/1

### Modifie un trip OK

PATCH http://localhost:5000/api/trips/2
content-type: application/json

{
    "type_trip": "DIRECT",
    "boat": "BRÉHATINE",
    "harbour": "ARCOUEST",
    "departure": "15:35",
    "arrival": null,
    "day_trip": "2023-01-09",
    "quantity": 59,
    "delay_trip": "true",
    "reason": "",
    "user_id_": 2
}

### Supprime un trip OK

DELETE  http://process.ENV.URL/api/trips/5

### Login

POST http://localhost:5000/api/login
content-type: application/json

{
    "email": "carlos@vvdb.fr",
    "password": "Hello22+"
}